title:       Flyknife Comics
description: "All The Snakepunk that the Battery Can’t Stop"
aside_message: "Welcome one and all to the FLYKNIFE COMIX WEBZONE. Here you will find all the neat deets and slick tricks you’ll need to fight R.A.N.C.O.U.R and Commander Zeta. Deck fast, Deckers, the Apocalypse Clock is ticking."

author:         Bruce Delo
author_twitter: FlyknifeComics

url:     http://beta.flyknifecomics.com
baseurl: ""

url_twitter: https://twitter.com/FlyknifeComics

color_brand: BAD455

copyright:     Creative Commons Attribution-NonCommercial-ShareAlike 4.0 Unported
url_copyright: http://creativecommons.org/licenses/by-nc-sa/4.0/deed.en

timezone: America/Halifax

destination: ./_site
layouts: ./_layouts
permalink: /:categories/:title/
exclude: ['node_modules', '.sass-cache']

paginate: 10
paginate_path: 'page:num'

gems:
- jekyll-redirect-from
- jekyll-sitemap
- jemoji
