title:       Flyknife Comics
tagline:     "All The Snakepunk that the Battery Can’t Stop"
lede:        "Welcome one and all to the FLYKNIFE COMIX WEBZONE. Here you will find all the neat deets and slick tricks you’ll need to fight R.A.N.C.O.U.R and Commander Zeta. Deck fast, Deckers, the Apocalypse Clock is ticking."
color_brand: 8cddff

author:          Bruce Delo
author_location: Halifax, NS
author_twitter:  FlyknifeComics

url:     https://flyknifecomics.com
baseurl: ""

url_twitter: https://twitter.com/FlyknifeComics

copyright:     Creative Commons Attribution-NonCommercial-ShareAlike 4.0 Unported
url_copyright: http://creativecommons.org/licenses/by-nc-sa/4.0/deed.en

sitemap_changefreq: monthly
sitemap_priority:   0.5

timezone: America/Halifax

destination: ./_site
layouts_dir: ./_layouts
permalink: /:categories/:title/
exclude: ['node_modules', '.sass-cache', 'src']
incremental: true

gems:
- jekyll-redirect-from
